fragment SettingsParts on Settings {
  __typename
  siteName
  homeTitle
  tagline
  metaDescriptionFa
  heroKicker
  heroTitle
  heroTitleSuffix
  heroParagraph
  heroCtaLabel
  aboutKicker
  aboutTitle
  aboutParagraph
  booksKicker
  booksTitle
  booksParagraph
  videosKicker
  videosTitle
  videosParagraph
  liveKicker
  liveTitle
  liveParagraph
  channelsKicker
  channelsTitle
  channelsParagraph
  ctaTitle
  ctaParagraph
  tiktokApiBase
  tiktokRefreshMs
  footerNote
}

fragment BooksParts on Books {
  __typename
  variant
  coverImage
  coverAlt
  coverRatio
  restRotateY
  restRotateX
  spineLabel
  titleFa
  descriptionFa
  pdfUrl
  audioUrl
  officialUrl
}

fragment YoutubeParts on Youtube {
  __typename
  kicker
  title
  channelUrl
  channelAriaLabel
  channelImage
  channelImageAlt
  channelCta
  videos {
    __typename
    url
    autoTitle
    thumb
    thumbAlt
    channelLabel
    title
    ctaLabel
  }
}

fragment TiktokParts on Tiktok {
  __typename
  username
  displayName
  profileUrl
  avatar
  ariaLabel
  official
  language
  order
  featured
}

fragment StudyParts on Study {
  __typename
  pageTitle
  sections {
    __typename
    num
    title
    blocks {
      __typename
      ... on StudySectionsBlocksParagraph {
        text
      }
      ... on StudySectionsBlocksFinalNote {
        text
      }
      ... on StudySectionsBlocksSubheading {
        text
      }
      ... on StudySectionsBlocksQuote {
        text
        source
      }
    }
  }
}
