//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  import type { TinaMarkdownContent } from 'tinacms/dist/rich-text';
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
  /** A rich-text document, renderable by TinaMarkdown */
  RichText: { input: TinaMarkdownContent; output: TinaMarkdownContent; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  settings: Settings;
  settingsConnection: SettingsConnection;
  books: Books;
  booksConnection: BooksConnection;
  youtube: Youtube;
  youtubeConnection: YoutubeConnection;
  tiktok: Tiktok;
  tiktokConnection: TiktokConnection;
  study: Study;
  studyConnection: StudyConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
};


export type QueryBooksArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBooksConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BooksFilter>;
};


export type QueryYoutubeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryYoutubeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<YoutubeFilter>;
};


export type QueryTiktokArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTiktokConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TiktokFilter>;
};


export type QueryStudyArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryStudyConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StudyFilter>;
};

export type DocumentFilter = {
  settings?: InputMaybe<SettingsFilter>;
  books?: InputMaybe<BooksFilter>;
  youtube?: InputMaybe<YoutubeFilter>;
  tiktok?: InputMaybe<TiktokFilter>;
  study?: InputMaybe<StudyFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Settings | Books | Youtube | Tiktok | Study | Folder;

export type Settings = Node & Document & {
  __typename?: 'Settings';
  siteName?: Maybe<Scalars['String']['output']>;
  homeTitle?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  metaDescriptionFa?: Maybe<Scalars['String']['output']>;
  heroKicker?: Maybe<Scalars['String']['output']>;
  heroTitle?: Maybe<Scalars['String']['output']>;
  heroTitleSuffix?: Maybe<Scalars['String']['output']>;
  heroParagraph?: Maybe<Scalars['String']['output']>;
  heroCtaLabel?: Maybe<Scalars['String']['output']>;
  aboutKicker?: Maybe<Scalars['String']['output']>;
  aboutTitle?: Maybe<Scalars['String']['output']>;
  aboutParagraph?: Maybe<Scalars['String']['output']>;
  booksKicker?: Maybe<Scalars['String']['output']>;
  booksTitle?: Maybe<Scalars['String']['output']>;
  booksParagraph?: Maybe<Scalars['String']['output']>;
  videosKicker?: Maybe<Scalars['String']['output']>;
  videosTitle?: Maybe<Scalars['String']['output']>;
  videosParagraph?: Maybe<Scalars['String']['output']>;
  liveKicker?: Maybe<Scalars['String']['output']>;
  liveTitle?: Maybe<Scalars['String']['output']>;
  liveParagraph?: Maybe<Scalars['String']['output']>;
  channelsKicker?: Maybe<Scalars['String']['output']>;
  channelsTitle?: Maybe<Scalars['String']['output']>;
  channelsParagraph?: Maybe<Scalars['String']['output']>;
  ctaTitle?: Maybe<Scalars['String']['output']>;
  ctaParagraph?: Maybe<Scalars['String']['output']>;
  tiktokApiBase?: Maybe<Scalars['String']['output']>;
  tiktokRefreshMs?: Maybe<Scalars['Float']['output']>;
  footerNote?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type SettingsFilter = {
  siteName?: InputMaybe<StringFilter>;
  homeTitle?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  metaDescriptionFa?: InputMaybe<StringFilter>;
  heroKicker?: InputMaybe<StringFilter>;
  heroTitle?: InputMaybe<StringFilter>;
  heroTitleSuffix?: InputMaybe<StringFilter>;
  heroParagraph?: InputMaybe<StringFilter>;
  heroCtaLabel?: InputMaybe<StringFilter>;
  aboutKicker?: InputMaybe<StringFilter>;
  aboutTitle?: InputMaybe<StringFilter>;
  aboutParagraph?: InputMaybe<StringFilter>;
  booksKicker?: InputMaybe<StringFilter>;
  booksTitle?: InputMaybe<StringFilter>;
  booksParagraph?: InputMaybe<StringFilter>;
  videosKicker?: InputMaybe<StringFilter>;
  videosTitle?: InputMaybe<StringFilter>;
  videosParagraph?: InputMaybe<StringFilter>;
  liveKicker?: InputMaybe<StringFilter>;
  liveTitle?: InputMaybe<StringFilter>;
  liveParagraph?: InputMaybe<StringFilter>;
  channelsKicker?: InputMaybe<StringFilter>;
  channelsTitle?: InputMaybe<StringFilter>;
  channelsParagraph?: InputMaybe<StringFilter>;
  ctaTitle?: InputMaybe<StringFilter>;
  ctaParagraph?: InputMaybe<StringFilter>;
  tiktokApiBase?: InputMaybe<StringFilter>;
  tiktokRefreshMs?: InputMaybe<NumberFilter>;
  footerNote?: InputMaybe<StringFilter>;
};

export type SettingsConnectionEdges = {
  __typename?: 'SettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Settings>;
};

export type SettingsConnection = Connection & {
  __typename?: 'SettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SettingsConnectionEdges>>>;
};

export type Books = Node & Document & {
  __typename?: 'Books';
  variant?: Maybe<Scalars['String']['output']>;
  coverImage?: Maybe<Scalars['String']['output']>;
  coverAlt?: Maybe<Scalars['String']['output']>;
  coverRatio?: Maybe<Scalars['Float']['output']>;
  restRotateY?: Maybe<Scalars['Float']['output']>;
  restRotateX?: Maybe<Scalars['Float']['output']>;
  spineLabel?: Maybe<Scalars['String']['output']>;
  titleFa?: Maybe<Scalars['String']['output']>;
  descriptionFa?: Maybe<Scalars['String']['output']>;
  pdfUrl?: Maybe<Scalars['String']['output']>;
  audioUrl?: Maybe<Scalars['String']['output']>;
  officialUrl?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooksFilter = {
  variant?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  coverAlt?: InputMaybe<StringFilter>;
  coverRatio?: InputMaybe<NumberFilter>;
  restRotateY?: InputMaybe<NumberFilter>;
  restRotateX?: InputMaybe<NumberFilter>;
  spineLabel?: InputMaybe<StringFilter>;
  titleFa?: InputMaybe<StringFilter>;
  descriptionFa?: InputMaybe<StringFilter>;
  pdfUrl?: InputMaybe<StringFilter>;
  audioUrl?: InputMaybe<StringFilter>;
  officialUrl?: InputMaybe<StringFilter>;
};

export type BooksConnectionEdges = {
  __typename?: 'BooksConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Books>;
};

export type BooksConnection = Connection & {
  __typename?: 'BooksConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BooksConnectionEdges>>>;
};

export type YoutubeVideos = {
  __typename?: 'YoutubeVideos';
  url?: Maybe<Scalars['String']['output']>;
  autoTitle?: Maybe<Scalars['Boolean']['output']>;
  thumb?: Maybe<Scalars['String']['output']>;
  thumbAlt?: Maybe<Scalars['String']['output']>;
  channelLabel?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  ctaLabel?: Maybe<Scalars['String']['output']>;
};

export type Youtube = Node & Document & {
  __typename?: 'Youtube';
  kicker?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  channelUrl?: Maybe<Scalars['String']['output']>;
  channelAriaLabel?: Maybe<Scalars['String']['output']>;
  channelImage?: Maybe<Scalars['String']['output']>;
  channelImageAlt?: Maybe<Scalars['String']['output']>;
  channelCta?: Maybe<Scalars['String']['output']>;
  videos?: Maybe<Array<Maybe<YoutubeVideos>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type YoutubeVideosFilter = {
  url?: InputMaybe<StringFilter>;
  autoTitle?: InputMaybe<BooleanFilter>;
  thumb?: InputMaybe<StringFilter>;
  thumbAlt?: InputMaybe<StringFilter>;
  channelLabel?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  ctaLabel?: InputMaybe<StringFilter>;
};

export type YoutubeFilter = {
  kicker?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  channelUrl?: InputMaybe<StringFilter>;
  channelAriaLabel?: InputMaybe<StringFilter>;
  channelImage?: InputMaybe<ImageFilter>;
  channelImageAlt?: InputMaybe<StringFilter>;
  channelCta?: InputMaybe<StringFilter>;
  videos?: InputMaybe<YoutubeVideosFilter>;
};

export type YoutubeConnectionEdges = {
  __typename?: 'YoutubeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Youtube>;
};

export type YoutubeConnection = Connection & {
  __typename?: 'YoutubeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<YoutubeConnectionEdges>>>;
};

export type Tiktok = Node & Document & {
  __typename?: 'Tiktok';
  username?: Maybe<Scalars['String']['output']>;
  displayName?: Maybe<Scalars['String']['output']>;
  profileUrl?: Maybe<Scalars['String']['output']>;
  avatar?: Maybe<Scalars['String']['output']>;
  ariaLabel?: Maybe<Scalars['String']['output']>;
  official?: Maybe<Scalars['Boolean']['output']>;
  language?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TiktokFilter = {
  username?: InputMaybe<StringFilter>;
  displayName?: InputMaybe<StringFilter>;
  profileUrl?: InputMaybe<StringFilter>;
  avatar?: InputMaybe<ImageFilter>;
  ariaLabel?: InputMaybe<StringFilter>;
  official?: InputMaybe<BooleanFilter>;
  language?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  featured?: InputMaybe<BooleanFilter>;
};

export type TiktokConnectionEdges = {
  __typename?: 'TiktokConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Tiktok>;
};

export type TiktokConnection = Connection & {
  __typename?: 'TiktokConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TiktokConnectionEdges>>>;
};

export type StudySectionsBlocksParagraph = {
  __typename?: 'StudySectionsBlocksParagraph';
  text?: Maybe<Scalars['String']['output']>;
};

export type StudySectionsBlocksFinalNote = {
  __typename?: 'StudySectionsBlocksFinalNote';
  text?: Maybe<Scalars['String']['output']>;
};

export type StudySectionsBlocksSubheading = {
  __typename?: 'StudySectionsBlocksSubheading';
  text?: Maybe<Scalars['String']['output']>;
};

export type StudySectionsBlocksQuote = {
  __typename?: 'StudySectionsBlocksQuote';
  text?: Maybe<Scalars['String']['output']>;
  source?: Maybe<Scalars['String']['output']>;
};

export type StudySectionsBlocks = StudySectionsBlocksParagraph | StudySectionsBlocksFinalNote | StudySectionsBlocksSubheading | StudySectionsBlocksQuote;

export type StudySections = {
  __typename?: 'StudySections';
  num?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  blocks?: Maybe<Array<Maybe<StudySectionsBlocks>>>;
};

export type Study = Node & Document & {
  __typename?: 'Study';
  pageTitle?: Maybe<Scalars['String']['output']>;
  sections?: Maybe<Array<Maybe<StudySections>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StudySectionsBlocksParagraphFilter = {
  text?: InputMaybe<StringFilter>;
};

export type StudySectionsBlocksFinalNoteFilter = {
  text?: InputMaybe<StringFilter>;
};

export type StudySectionsBlocksSubheadingFilter = {
  text?: InputMaybe<StringFilter>;
};

export type StudySectionsBlocksQuoteFilter = {
  text?: InputMaybe<StringFilter>;
  source?: InputMaybe<StringFilter>;
};

export type StudySectionsBlocksFilter = {
  paragraph?: InputMaybe<StudySectionsBlocksParagraphFilter>;
  finalNote?: InputMaybe<StudySectionsBlocksFinalNoteFilter>;
  subheading?: InputMaybe<StudySectionsBlocksSubheadingFilter>;
  quote?: InputMaybe<StudySectionsBlocksQuoteFilter>;
};

export type StudySectionsFilter = {
  num?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  blocks?: InputMaybe<StudySectionsBlocksFilter>;
};

export type StudyFilter = {
  pageTitle?: InputMaybe<StringFilter>;
  sections?: InputMaybe<StudySectionsFilter>;
};

export type StudyConnectionEdges = {
  __typename?: 'StudyConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Study>;
};

export type StudyConnection = Connection & {
  __typename?: 'StudyConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<StudyConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSettings: Settings;
  createSettings: Settings;
  updateBooks: Books;
  createBooks: Books;
  updateYoutube: Youtube;
  createYoutube: Youtube;
  updateTiktok: Tiktok;
  createTiktok: Tiktok;
  updateStudy: Study;
  createStudy: Study;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationCreateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationUpdateBooksArgs = {
  relativePath: Scalars['String']['input'];
  params: BooksMutation;
};


export type MutationCreateBooksArgs = {
  relativePath: Scalars['String']['input'];
  params: BooksMutation;
};


export type MutationUpdateYoutubeArgs = {
  relativePath: Scalars['String']['input'];
  params: YoutubeMutation;
};


export type MutationCreateYoutubeArgs = {
  relativePath: Scalars['String']['input'];
  params: YoutubeMutation;
};


export type MutationUpdateTiktokArgs = {
  relativePath: Scalars['String']['input'];
  params: TiktokMutation;
};


export type MutationCreateTiktokArgs = {
  relativePath: Scalars['String']['input'];
  params: TiktokMutation;
};


export type MutationUpdateStudyArgs = {
  relativePath: Scalars['String']['input'];
  params: StudyMutation;
};


export type MutationCreateStudyArgs = {
  relativePath: Scalars['String']['input'];
  params: StudyMutation;
};

export type DocumentUpdateMutation = {
  settings?: InputMaybe<SettingsMutation>;
  books?: InputMaybe<BooksMutation>;
  youtube?: InputMaybe<YoutubeMutation>;
  tiktok?: InputMaybe<TiktokMutation>;
  study?: InputMaybe<StudyMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  settings?: InputMaybe<SettingsMutation>;
  books?: InputMaybe<BooksMutation>;
  youtube?: InputMaybe<YoutubeMutation>;
  tiktok?: InputMaybe<TiktokMutation>;
  study?: InputMaybe<StudyMutation>;
};

export type SettingsMutation = {
  siteName?: InputMaybe<Scalars['String']['input']>;
  homeTitle?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  metaDescriptionFa?: InputMaybe<Scalars['String']['input']>;
  heroKicker?: InputMaybe<Scalars['String']['input']>;
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  heroTitleSuffix?: InputMaybe<Scalars['String']['input']>;
  heroParagraph?: InputMaybe<Scalars['String']['input']>;
  heroCtaLabel?: InputMaybe<Scalars['String']['input']>;
  aboutKicker?: InputMaybe<Scalars['String']['input']>;
  aboutTitle?: InputMaybe<Scalars['String']['input']>;
  aboutParagraph?: InputMaybe<Scalars['String']['input']>;
  booksKicker?: InputMaybe<Scalars['String']['input']>;
  booksTitle?: InputMaybe<Scalars['String']['input']>;
  booksParagraph?: InputMaybe<Scalars['String']['input']>;
  videosKicker?: InputMaybe<Scalars['String']['input']>;
  videosTitle?: InputMaybe<Scalars['String']['input']>;
  videosParagraph?: InputMaybe<Scalars['String']['input']>;
  liveKicker?: InputMaybe<Scalars['String']['input']>;
  liveTitle?: InputMaybe<Scalars['String']['input']>;
  liveParagraph?: InputMaybe<Scalars['String']['input']>;
  channelsKicker?: InputMaybe<Scalars['String']['input']>;
  channelsTitle?: InputMaybe<Scalars['String']['input']>;
  channelsParagraph?: InputMaybe<Scalars['String']['input']>;
  ctaTitle?: InputMaybe<Scalars['String']['input']>;
  ctaParagraph?: InputMaybe<Scalars['String']['input']>;
  tiktokApiBase?: InputMaybe<Scalars['String']['input']>;
  tiktokRefreshMs?: InputMaybe<Scalars['Float']['input']>;
  footerNote?: InputMaybe<Scalars['String']['input']>;
};

export type BooksMutation = {
  variant?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  coverAlt?: InputMaybe<Scalars['String']['input']>;
  coverRatio?: InputMaybe<Scalars['Float']['input']>;
  restRotateY?: InputMaybe<Scalars['Float']['input']>;
  restRotateX?: InputMaybe<Scalars['Float']['input']>;
  spineLabel?: InputMaybe<Scalars['String']['input']>;
  titleFa?: InputMaybe<Scalars['String']['input']>;
  descriptionFa?: InputMaybe<Scalars['String']['input']>;
  pdfUrl?: InputMaybe<Scalars['String']['input']>;
  audioUrl?: InputMaybe<Scalars['String']['input']>;
  officialUrl?: InputMaybe<Scalars['String']['input']>;
};

export type YoutubeVideosMutation = {
  url?: InputMaybe<Scalars['String']['input']>;
  autoTitle?: InputMaybe<Scalars['Boolean']['input']>;
  thumb?: InputMaybe<Scalars['String']['input']>;
  thumbAlt?: InputMaybe<Scalars['String']['input']>;
  channelLabel?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  ctaLabel?: InputMaybe<Scalars['String']['input']>;
};

export type YoutubeMutation = {
  kicker?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  channelUrl?: InputMaybe<Scalars['String']['input']>;
  channelAriaLabel?: InputMaybe<Scalars['String']['input']>;
  channelImage?: InputMaybe<Scalars['String']['input']>;
  channelImageAlt?: InputMaybe<Scalars['String']['input']>;
  channelCta?: InputMaybe<Scalars['String']['input']>;
  videos?: InputMaybe<Array<InputMaybe<YoutubeVideosMutation>>>;
};

export type TiktokMutation = {
  username?: InputMaybe<Scalars['String']['input']>;
  displayName?: InputMaybe<Scalars['String']['input']>;
  profileUrl?: InputMaybe<Scalars['String']['input']>;
  avatar?: InputMaybe<Scalars['String']['input']>;
  ariaLabel?: InputMaybe<Scalars['String']['input']>;
  official?: InputMaybe<Scalars['Boolean']['input']>;
  language?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
};

export type StudySectionsBlocksParagraphMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
};

export type StudySectionsBlocksFinalNoteMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
};

export type StudySectionsBlocksSubheadingMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
};

export type StudySectionsBlocksQuoteMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  source?: InputMaybe<Scalars['String']['input']>;
};

export type StudySectionsBlocksMutation = {
  paragraph?: InputMaybe<StudySectionsBlocksParagraphMutation>;
  finalNote?: InputMaybe<StudySectionsBlocksFinalNoteMutation>;
  subheading?: InputMaybe<StudySectionsBlocksSubheadingMutation>;
  quote?: InputMaybe<StudySectionsBlocksQuoteMutation>;
};

export type StudySectionsMutation = {
  num?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  blocks?: InputMaybe<Array<InputMaybe<StudySectionsBlocksMutation>>>;
};

export type StudyMutation = {
  pageTitle?: InputMaybe<Scalars['String']['input']>;
  sections?: InputMaybe<Array<InputMaybe<StudySectionsMutation>>>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type NumberFilter = {
  lt?: number | null | undefined;
  lte?: number | null | undefined;
  gte?: number | null | undefined;
  gt?: number | null | undefined;
  eq?: number | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<number | null | undefined> | null | undefined;
};

export type SettingsFilter = {
  siteName?: StringFilter | null | undefined;
  homeTitle?: StringFilter | null | undefined;
  tagline?: StringFilter | null | undefined;
  metaDescriptionFa?: StringFilter | null | undefined;
  heroKicker?: StringFilter | null | undefined;
  heroTitle?: StringFilter | null | undefined;
  heroTitleSuffix?: StringFilter | null | undefined;
  heroParagraph?: StringFilter | null | undefined;
  heroCtaLabel?: StringFilter | null | undefined;
  aboutKicker?: StringFilter | null | undefined;
  aboutTitle?: StringFilter | null | undefined;
  aboutParagraph?: StringFilter | null | undefined;
  booksKicker?: StringFilter | null | undefined;
  booksTitle?: StringFilter | null | undefined;
  booksParagraph?: StringFilter | null | undefined;
  videosKicker?: StringFilter | null | undefined;
  videosTitle?: StringFilter | null | undefined;
  videosParagraph?: StringFilter | null | undefined;
  liveKicker?: StringFilter | null | undefined;
  liveTitle?: StringFilter | null | undefined;
  liveParagraph?: StringFilter | null | undefined;
  channelsKicker?: StringFilter | null | undefined;
  channelsTitle?: StringFilter | null | undefined;
  channelsParagraph?: StringFilter | null | undefined;
  ctaTitle?: StringFilter | null | undefined;
  ctaParagraph?: StringFilter | null | undefined;
  tiktokApiBase?: StringFilter | null | undefined;
  tiktokRefreshMs?: NumberFilter | null | undefined;
  footerNote?: StringFilter | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type BooksFilter = {
  variant?: StringFilter | null | undefined;
  coverImage?: ImageFilter | null | undefined;
  coverAlt?: StringFilter | null | undefined;
  coverRatio?: NumberFilter | null | undefined;
  restRotateY?: NumberFilter | null | undefined;
  restRotateX?: NumberFilter | null | undefined;
  spineLabel?: StringFilter | null | undefined;
  titleFa?: StringFilter | null | undefined;
  descriptionFa?: StringFilter | null | undefined;
  pdfUrl?: StringFilter | null | undefined;
  audioUrl?: StringFilter | null | undefined;
  officialUrl?: StringFilter | null | undefined;
};

export type BooleanFilter = {
  eq?: boolean | null | undefined;
  exists?: boolean | null | undefined;
};

export type YoutubeVideosFilter = {
  url?: StringFilter | null | undefined;
  autoTitle?: BooleanFilter | null | undefined;
  thumb?: StringFilter | null | undefined;
  thumbAlt?: StringFilter | null | undefined;
  channelLabel?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  ctaLabel?: StringFilter | null | undefined;
};

export type YoutubeFilter = {
  kicker?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  channelUrl?: StringFilter | null | undefined;
  channelAriaLabel?: StringFilter | null | undefined;
  channelImage?: ImageFilter | null | undefined;
  channelImageAlt?: StringFilter | null | undefined;
  channelCta?: StringFilter | null | undefined;
  videos?: YoutubeVideosFilter | null | undefined;
};

export type TiktokFilter = {
  username?: StringFilter | null | undefined;
  displayName?: StringFilter | null | undefined;
  profileUrl?: StringFilter | null | undefined;
  avatar?: ImageFilter | null | undefined;
  ariaLabel?: StringFilter | null | undefined;
  official?: BooleanFilter | null | undefined;
  language?: StringFilter | null | undefined;
  order?: NumberFilter | null | undefined;
  featured?: BooleanFilter | null | undefined;
};

export type StudySectionsBlocksParagraphFilter = {
  text?: StringFilter | null | undefined;
};

export type StudySectionsBlocksFinalNoteFilter = {
  text?: StringFilter | null | undefined;
};

export type StudySectionsBlocksSubheadingFilter = {
  text?: StringFilter | null | undefined;
};

export type StudySectionsBlocksQuoteFilter = {
  text?: StringFilter | null | undefined;
  source?: StringFilter | null | undefined;
};

export type StudySectionsBlocksFilter = {
  paragraph?: StudySectionsBlocksParagraphFilter | null | undefined;
  finalNote?: StudySectionsBlocksFinalNoteFilter | null | undefined;
  subheading?: StudySectionsBlocksSubheadingFilter | null | undefined;
  quote?: StudySectionsBlocksQuoteFilter | null | undefined;
};

export type StudySectionsFilter = {
  num?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  blocks?: StudySectionsBlocksFilter | null | undefined;
};

export type StudyFilter = {
  pageTitle?: StringFilter | null | undefined;
  sections?: StudySectionsFilter | null | undefined;
};

export type SettingsPartsFragment = { __typename: 'Settings', siteName: string | null, homeTitle: string | null, tagline: string | null, metaDescriptionFa: string | null, heroKicker: string | null, heroTitle: string | null, heroTitleSuffix: string | null, heroParagraph: string | null, heroCtaLabel: string | null, aboutKicker: string | null, aboutTitle: string | null, aboutParagraph: string | null, booksKicker: string | null, booksTitle: string | null, booksParagraph: string | null, videosKicker: string | null, videosTitle: string | null, videosParagraph: string | null, liveKicker: string | null, liveTitle: string | null, liveParagraph: string | null, channelsKicker: string | null, channelsTitle: string | null, channelsParagraph: string | null, ctaTitle: string | null, ctaParagraph: string | null, tiktokApiBase: string | null, tiktokRefreshMs: number | null, footerNote: string | null };

export type BooksPartsFragment = { __typename: 'Books', variant: string | null, coverImage: string | null, coverAlt: string | null, coverRatio: number | null, restRotateY: number | null, restRotateX: number | null, spineLabel: string | null, titleFa: string | null, descriptionFa: string | null, pdfUrl: string | null, audioUrl: string | null, officialUrl: string | null };

export type YoutubePartsFragment = { __typename: 'Youtube', kicker: string | null, title: string | null, channelUrl: string | null, channelAriaLabel: string | null, channelImage: string | null, channelImageAlt: string | null, channelCta: string | null, videos: Array<{ __typename: 'YoutubeVideos', url: string | null, autoTitle: boolean | null, thumb: string | null, thumbAlt: string | null, channelLabel: string | null, title: string | null, ctaLabel: string | null } | null> | null };

export type TiktokPartsFragment = { __typename: 'Tiktok', username: string | null, displayName: string | null, profileUrl: string | null, avatar: string | null, ariaLabel: string | null, official: boolean | null, language: string | null, order: number | null, featured: boolean | null };

export type StudyPartsFragment = { __typename: 'Study', pageTitle: string | null, sections: Array<{ __typename: 'StudySections', num: string | null, title: string | null, blocks: Array<
      | { __typename: 'StudySectionsBlocksParagraph', text: string | null }
      | { __typename: 'StudySectionsBlocksFinalNote', text: string | null }
      | { __typename: 'StudySectionsBlocksSubheading', text: string | null }
      | { __typename: 'StudySectionsBlocksQuote', text: string | null, source: string | null }
     | null> | null } | null> | null };

export type SettingsQueryVariables = Exact<{
  relativePath: string;
}>;


export type SettingsQuery = { settings: { __typename: 'Settings', id: string, siteName: string | null, homeTitle: string | null, tagline: string | null, metaDescriptionFa: string | null, heroKicker: string | null, heroTitle: string | null, heroTitleSuffix: string | null, heroParagraph: string | null, heroCtaLabel: string | null, aboutKicker: string | null, aboutTitle: string | null, aboutParagraph: string | null, booksKicker: string | null, booksTitle: string | null, booksParagraph: string | null, videosKicker: string | null, videosTitle: string | null, videosParagraph: string | null, liveKicker: string | null, liveTitle: string | null, liveParagraph: string | null, channelsKicker: string | null, channelsTitle: string | null, channelsParagraph: string | null, ctaTitle: string | null, ctaParagraph: string | null, tiktokApiBase: string | null, tiktokRefreshMs: number | null, footerNote: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SettingsConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: SettingsFilter | null | undefined;
}>;


export type SettingsConnectionQuery = { settingsConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Settings', id: string, siteName: string | null, homeTitle: string | null, tagline: string | null, metaDescriptionFa: string | null, heroKicker: string | null, heroTitle: string | null, heroTitleSuffix: string | null, heroParagraph: string | null, heroCtaLabel: string | null, aboutKicker: string | null, aboutTitle: string | null, aboutParagraph: string | null, booksKicker: string | null, booksTitle: string | null, booksParagraph: string | null, videosKicker: string | null, videosTitle: string | null, videosParagraph: string | null, liveKicker: string | null, liveTitle: string | null, liveParagraph: string | null, channelsKicker: string | null, channelsTitle: string | null, channelsParagraph: string | null, ctaTitle: string | null, ctaParagraph: string | null, tiktokApiBase: string | null, tiktokRefreshMs: number | null, footerNote: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type BooksQueryVariables = Exact<{
  relativePath: string;
}>;


export type BooksQuery = { books: { __typename: 'Books', id: string, variant: string | null, coverImage: string | null, coverAlt: string | null, coverRatio: number | null, restRotateY: number | null, restRotateX: number | null, spineLabel: string | null, titleFa: string | null, descriptionFa: string | null, pdfUrl: string | null, audioUrl: string | null, officialUrl: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BooksConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: BooksFilter | null | undefined;
}>;


export type BooksConnectionQuery = { booksConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Books', id: string, variant: string | null, coverImage: string | null, coverAlt: string | null, coverRatio: number | null, restRotateY: number | null, restRotateX: number | null, spineLabel: string | null, titleFa: string | null, descriptionFa: string | null, pdfUrl: string | null, audioUrl: string | null, officialUrl: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type YoutubeQueryVariables = Exact<{
  relativePath: string;
}>;


export type YoutubeQuery = { youtube: { __typename: 'Youtube', id: string, kicker: string | null, title: string | null, channelUrl: string | null, channelAriaLabel: string | null, channelImage: string | null, channelImageAlt: string | null, channelCta: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, videos: Array<{ __typename: 'YoutubeVideos', url: string | null, autoTitle: boolean | null, thumb: string | null, thumbAlt: string | null, channelLabel: string | null, title: string | null, ctaLabel: string | null } | null> | null } };

export type YoutubeConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: YoutubeFilter | null | undefined;
}>;


export type YoutubeConnectionQuery = { youtubeConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Youtube', id: string, kicker: string | null, title: string | null, channelUrl: string | null, channelAriaLabel: string | null, channelImage: string | null, channelImageAlt: string | null, channelCta: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, videos: Array<{ __typename: 'YoutubeVideos', url: string | null, autoTitle: boolean | null, thumb: string | null, thumbAlt: string | null, channelLabel: string | null, title: string | null, ctaLabel: string | null } | null> | null } | null } | null> | null } };

export type TiktokQueryVariables = Exact<{
  relativePath: string;
}>;


export type TiktokQuery = { tiktok: { __typename: 'Tiktok', id: string, username: string | null, displayName: string | null, profileUrl: string | null, avatar: string | null, ariaLabel: string | null, official: boolean | null, language: string | null, order: number | null, featured: boolean | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TiktokConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: TiktokFilter | null | undefined;
}>;


export type TiktokConnectionQuery = { tiktokConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Tiktok', id: string, username: string | null, displayName: string | null, profileUrl: string | null, avatar: string | null, ariaLabel: string | null, official: boolean | null, language: string | null, order: number | null, featured: boolean | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type StudyQueryVariables = Exact<{
  relativePath: string;
}>;


export type StudyQuery = { study: { __typename: 'Study', id: string, pageTitle: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections: Array<{ __typename: 'StudySections', num: string | null, title: string | null, blocks: Array<
        | { __typename: 'StudySectionsBlocksParagraph', text: string | null }
        | { __typename: 'StudySectionsBlocksFinalNote', text: string | null }
        | { __typename: 'StudySectionsBlocksSubheading', text: string | null }
        | { __typename: 'StudySectionsBlocksQuote', text: string | null, source: string | null }
       | null> | null } | null> | null } };

export type StudyConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: StudyFilter | null | undefined;
}>;


export type StudyConnectionQuery = { studyConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Study', id: string, pageTitle: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections: Array<{ __typename: 'StudySections', num: string | null, title: string | null, blocks: Array<
            | { __typename: 'StudySectionsBlocksParagraph', text: string | null }
            | { __typename: 'StudySectionsBlocksFinalNote', text: string | null }
            | { __typename: 'StudySectionsBlocksSubheading', text: string | null }
            | { __typename: 'StudySectionsBlocksQuote', text: string | null, source: string | null }
           | null> | null } | null> | null } | null } | null> | null } };

export const SettingsPartsFragmentDoc = gql`
    fragment SettingsParts on Settings {
  __typename
  siteName
  homeTitle
  tagline
  metaDescriptionFa
  heroKicker
  heroTitle
  heroTitleSuffix
  heroParagraph
  heroCtaLabel
  aboutKicker
  aboutTitle
  aboutParagraph
  booksKicker
  booksTitle
  booksParagraph
  videosKicker
  videosTitle
  videosParagraph
  liveKicker
  liveTitle
  liveParagraph
  channelsKicker
  channelsTitle
  channelsParagraph
  ctaTitle
  ctaParagraph
  tiktokApiBase
  tiktokRefreshMs
  footerNote
}
    `;
export const BooksPartsFragmentDoc = gql`
    fragment BooksParts on Books {
  __typename
  variant
  coverImage
  coverAlt
  coverRatio
  restRotateY
  restRotateX
  spineLabel
  titleFa
  descriptionFa
  pdfUrl
  audioUrl
  officialUrl
}
    `;
export const YoutubePartsFragmentDoc = gql`
    fragment YoutubeParts on Youtube {
  __typename
  kicker
  title
  channelUrl
  channelAriaLabel
  channelImage
  channelImageAlt
  channelCta
  videos {
    __typename
    url
    autoTitle
    thumb
    thumbAlt
    channelLabel
    title
    ctaLabel
  }
}
    `;
export const TiktokPartsFragmentDoc = gql`
    fragment TiktokParts on Tiktok {
  __typename
  username
  displayName
  profileUrl
  avatar
  ariaLabel
  official
  language
  order
  featured
}
    `;
export const StudyPartsFragmentDoc = gql`
    fragment StudyParts on Study {
  __typename
  pageTitle
  sections {
    __typename
    num
    title
    blocks {
      __typename
      ... on StudySectionsBlocksParagraph {
        text
      }
      ... on StudySectionsBlocksFinalNote {
        text
      }
      ... on StudySectionsBlocksSubheading {
        text
      }
      ... on StudySectionsBlocksQuote {
        text
        source
      }
    }
  }
}
    `;
export const SettingsDocument = gql`
    query settings($relativePath: String!) {
  settings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SettingsParts
  }
}
    ${SettingsPartsFragmentDoc}`;
export const SettingsConnectionDocument = gql`
    query settingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SettingsFilter) {
  settingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SettingsParts
      }
    }
  }
}
    ${SettingsPartsFragmentDoc}`;
export const BooksDocument = gql`
    query books($relativePath: String!) {
  books(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BooksParts
  }
}
    ${BooksPartsFragmentDoc}`;
export const BooksConnectionDocument = gql`
    query booksConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BooksFilter) {
  booksConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BooksParts
      }
    }
  }
}
    ${BooksPartsFragmentDoc}`;
export const YoutubeDocument = gql`
    query youtube($relativePath: String!) {
  youtube(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...YoutubeParts
  }
}
    ${YoutubePartsFragmentDoc}`;
export const YoutubeConnectionDocument = gql`
    query youtubeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: YoutubeFilter) {
  youtubeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...YoutubeParts
      }
    }
  }
}
    ${YoutubePartsFragmentDoc}`;
export const TiktokDocument = gql`
    query tiktok($relativePath: String!) {
  tiktok(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TiktokParts
  }
}
    ${TiktokPartsFragmentDoc}`;
export const TiktokConnectionDocument = gql`
    query tiktokConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TiktokFilter) {
  tiktokConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TiktokParts
      }
    }
  }
}
    ${TiktokPartsFragmentDoc}`;
export const StudyDocument = gql`
    query study($relativePath: String!) {
  study(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...StudyParts
  }
}
    ${StudyPartsFragmentDoc}`;
export const StudyConnectionDocument = gql`
    query studyConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: StudyFilter) {
  studyConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...StudyParts
      }
    }
  }
}
    ${StudyPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      settings(variables: SettingsQueryVariables, options?: C): Promise<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}> {
        return requester<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}, SettingsQueryVariables>(SettingsDocument, variables, options);
      },
    settingsConnection(variables?: SettingsConnectionQueryVariables, options?: C): Promise<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}, SettingsConnectionQueryVariables>(SettingsConnectionDocument, variables, options);
      },
    books(variables: BooksQueryVariables, options?: C): Promise<{data: BooksQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BooksQueryVariables, query: string}> {
        return requester<{data: BooksQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BooksQueryVariables, query: string}, BooksQueryVariables>(BooksDocument, variables, options);
      },
    booksConnection(variables?: BooksConnectionQueryVariables, options?: C): Promise<{data: BooksConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BooksConnectionQueryVariables, query: string}> {
        return requester<{data: BooksConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BooksConnectionQueryVariables, query: string}, BooksConnectionQueryVariables>(BooksConnectionDocument, variables, options);
      },
    youtube(variables: YoutubeQueryVariables, options?: C): Promise<{data: YoutubeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: YoutubeQueryVariables, query: string}> {
        return requester<{data: YoutubeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: YoutubeQueryVariables, query: string}, YoutubeQueryVariables>(YoutubeDocument, variables, options);
      },
    youtubeConnection(variables?: YoutubeConnectionQueryVariables, options?: C): Promise<{data: YoutubeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: YoutubeConnectionQueryVariables, query: string}> {
        return requester<{data: YoutubeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: YoutubeConnectionQueryVariables, query: string}, YoutubeConnectionQueryVariables>(YoutubeConnectionDocument, variables, options);
      },
    tiktok(variables: TiktokQueryVariables, options?: C): Promise<{data: TiktokQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TiktokQueryVariables, query: string}> {
        return requester<{data: TiktokQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TiktokQueryVariables, query: string}, TiktokQueryVariables>(TiktokDocument, variables, options);
      },
    tiktokConnection(variables?: TiktokConnectionQueryVariables, options?: C): Promise<{data: TiktokConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TiktokConnectionQueryVariables, query: string}> {
        return requester<{data: TiktokConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TiktokConnectionQueryVariables, query: string}, TiktokConnectionQueryVariables>(TiktokConnectionDocument, variables, options);
      },
    study(variables: StudyQueryVariables, options?: C): Promise<{data: StudyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StudyQueryVariables, query: string}> {
        return requester<{data: StudyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StudyQueryVariables, query: string}, StudyQueryVariables>(StudyDocument, variables, options);
      },
    studyConnection(variables?: StudyConnectionQueryVariables, options?: C): Promise<{data: StudyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StudyConnectionQueryVariables, query: string}> {
        return requester<{data: StudyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StudyConnectionQueryVariables, query: string}, StudyConnectionQueryVariables>(StudyConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  