#!/usr/bin/env python3
"""AROPL build step.

Runs AFTER `tinacms build --skip-cloud-checks` (which only emits the /admin
SPA). This script makes the static site actually consume the JSON content that
TinaCMS edits, without touching the existing HTML/CSS/JS design:

  1. Regenerates public/assets/js/tiktok-accounts.js from content/tiktok/*.json
     (the roster consumed by tiktok-live.js on every page).
  2. Injects window.AROPL_CONTENT (books, youtube, tiktok, settings) as a
     <script> block into index.html and study.html.
  3. Renders the Study article sections from content/study/*.json into
     study.html, preserving the existing markup structure and classes.
  4. Uses content/settings/site.json to refresh the editable copy in the shell.

Everything is derived from `content/` — no design values are hard-coded here.
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PUB = os.path.join(ROOT, "public")
CONTENT = os.path.join(ROOT, "content")


def load(path):
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def load_dir(sub):
    d = os.path.join(CONTENT, sub)
    out = []
    for name in sorted(os.listdir(d)):
        if name.endswith(".json"):
            out.append(load(os.path.join(d, name)))
    return out


def esc(s):
    return (
        str(s if s is not None else "")
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def write_roster(accounts):
    """Regenerate the shared TikTok roster used by the global LIVE alert."""
    ordered = [a for a in accounts if a.get("username")]
    ordered.sort(key=lambda a: (a.get("order", 0), a.get("username", "")))
    lines = [
        "/* GENERATED by scripts/build-content.py from content/tiktok/*.json — do not edit by hand.",
        "   Static profile metadata only; LIVE/OFFLINE status comes from the backend. */",
        "window.AROPL_TIKTOK_ACCOUNTS = [",
    ]
    for i, a in enumerate(ordered):
        official = "true" if a.get("official") else "false"
        lines.append(
            "  { username: %s, name: %s, official: %s }%s"
            % (json.dumps(a["username"], ensure_ascii=False),
               json.dumps(a["displayName"], ensure_ascii=False),
               official,
               "," if i < len(ordered) - 1 else "")
        )
    lines.append("];")
    path = os.path.join(PUB, "assets", "js", "tiktok-accounts.js")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def inject_content(html, payload):
    """Embed the JSON content as a global, escaped so it cannot break out."""
    blob = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    blob = blob.replace("<", "\\u003c")
    tag = ('<script id="aropl-content" type="application/json">'
           + blob + '</script>')

    def _repl(m):
        return tag

    html = re.sub(r'<script id="aropl-content"[^>]*>.*?</script>', _repl, html, flags=re.S)
    if tag not in html:
        html = html.replace('<script src="assets/js/config.js"></script>',
                            tag + '\n  <script src="assets/js/config.js"></script>')
    return html


def apply_settings(html, st):
    """Refresh editable shell copy that is not list-driven."""
    repl = [
        (r'(<meta name="description" content=")[^"]*(">)', st.get("metaDescriptionFa")),
        (r'(<title>)[^<]*(</title>)', st.get("siteName")),
        (r'(<div class="eyebrow">)[^<]*(</div>)', st.get("heroKicker")),
        (r'(<h1 id="hero-title">).*?(<br>)', esc(st.get("heroTitle")) + "<br>"),
        (r'(<h1 id="hero-title">.*?<span>)\([^<]*\)(</span></h1>)',
         "(" + esc(st.get("heroTitleSuffix")) + ")"),
    ]
    for pat, val in repl:
        if val:
            html = re.sub(pat, lambda m: m.group(1) + esc(val) + m.group(2), html, count=1)
    return html


def render_article(doc, lang):
    """Render one study article (FA or EN) from its JSON document."""
    out = []
    for i, sec in enumerate(doc.get("sections", [])):
        sid = "fa-" + re.sub(r"\D", "", sec.get("num", "")) if lang == "fa" else "en-" + re.sub(r"\D", "", sec.get("num", ""))
        # fall back to stable ids when numbering is not numeric
        sid = f"{lang}-{re.sub(r'[^0-9a-z]+', '-', (sec.get('num', str(i + 1)) or str(i + 1)).strip().lower()) or (i + 1)}"
        out.append(f'      <section class="article-section" id="{sid}">')
        out.append(f'        <h2><i class="sec-num">{esc(sec.get("num", ""))}</i><span>{esc(sec.get("title", ""))}</span></h2>')
        for b in sec.get("blocks", []):
            t = b.get("type")
            if t == "subheading":
                out.append(f'        <h3>{esc(b.get("text", ""))}</h3>')
            elif t == "quote":
                out.append('        <blockquote><p>%s</p><small>%s</small></blockquote>'
                           % (esc(b.get("text", "")), esc(b.get("source", ""))))
            elif t == "finalNote":
                out.append(f'        <p class="final-note">{esc(b.get("text", ""))}</p>')
            else:
                out.append(f'        <p>{esc(b.get("text", ""))}</p>')
        out.append("      </section>")
    return "\n".join(out)


def main():
    settings = load(os.path.join(CONTENT, "settings", "site.json"))
    books = load_dir("books")
    youtube = load_dir("youtube")
    accounts = load_dir("tiktok")
    study_fa = load(os.path.join(CONTENT, "study", "study-fa.json"))
    study_en = load(os.path.join(CONTENT, "study", "study-en.json"))

    write_roster(accounts)

    # regenerate config.js from settings
    with open(os.path.join(PUB, "assets", "js", "config.js"), "w", encoding="utf-8") as fh:
        fh.write(
            "/* Site configuration — GENERATED by scripts/build-content.py from content/settings/site.json.\n"
            "   TIKTOK_API_BASE is the public base URL of the tiktok-live-monitor backend\n"
            "   (no trailing slash). LIVE/OFFLINE detection always comes from that backend. */\n"
            "window.AROPL_CONFIG = {\n"
            "  TIKTOK_API_BASE: %s,\n"
            "  TIKTOK_REFRESH_MS: %s\n"
            "};\n" % (json.dumps(settings.get("tiktokApiBase", "")), json.dumps(settings.get("tiktokRefreshMs", 30000)))
        )

    payload = {
        "books": books,
        "youtubeBlocks": youtube,
        "tiktokAccounts": sorted([a for a in accounts if a.get("username")],
                                 key=lambda a: (a.get("order", 0), a.get("username", ""))),
        "settings": settings,
    }

    # ---------- index.html ----------
    with open(os.path.join(PUB, "index.html"), encoding="utf-8") as fh:
        index = fh.read()
    index = inject_content(index, payload)
    index = apply_settings(index, settings)
    with open(os.path.join(PUB, "index.html"), "w", encoding="utf-8") as fh:
        fh.write(index)

    # ---------- study.html ----------
    with open(os.path.join(PUB, "study.html"), encoding="utf-8") as fh:
        study = fh.read()
    study = inject_content(study, payload)
    study = apply_settings(study, settings)

    fa_art = re.search(r'(<article class="article-wrap study-version" id="study-fa"[^>]*>)(.*?)(\n    </article>)', study, re.S)
    en_art = re.search(r'(<article class="article-wrap study-version" id="study-en"[^>]*>)(.*?)(\n    </article>)', study, re.S)
    if fa_art:
        body = fa_art.group(2)
        intro = re.search(r'(<div class="article-intro">.*?</div>\s*</div>)', body, re.S)
        intro_html = intro.group(1) if intro else ""
        study = study[:fa_art.start(2)] + "\n" + intro_html + "\n" + render_article(study_fa, "fa") + "\n    " + study[fa_art.end(2):]
    if en_art:
        en_art = re.search(r'(<article class="article-wrap study-version" id="study-en"[^>]*>)(.*?)(\n    </article>)', study, re.S)
        body = en_art.group(2)
        intro = re.search(r'(<div class="article-intro">.*?</div>\s*</div>)', body, re.S)
        intro_html = intro.group(1) if intro else ""
        study = study[:en_art.start(2)] + "\n" + intro_html + "\n" + render_article(study_en, "en") + "\n    " + study[en_art.end(2):]

    with open(os.path.join(PUB, "study.html"), "w", encoding="utf-8") as fh:
        fh.write(study)

    print("[build-content] books=%d youtube=%d accounts=%d study_fa=%d study_en=%d"
          % (len(books), len(youtube), len(accounts), len(study_fa["sections"]), len(study_en["sections"])))


if __name__ == "__main__":
    sys.exit(main())
